# Generated by Django 4.2.1 on 2023-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo_model",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task", models.CharField(max_length=230)),
                ("completed", models.BooleanField(default=False)),
                ("created_At", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
